### ISSUE TITLE
What mud client should we use for this utf-8 version?

### ISSUE THREAD

**Issue by Yeeler** [fluffos/xkx100#1]
I tried Mushclient, the outbox is showing Chinese, but the input box just shows ASC II
Zmud 7.1, the outbox is showing ASC II while input box shows Chinese. 

:(

**Comment by thefallentree** [comment]
You should use the web interface .

**Comment by Yeeler** [comment]
Yes. I will try it out. Thanks for the suggestion.
I play fengyun since fy3, on and off for more than 15 years. Currently, I am converting it into utf8, so fluffOS can run it. 
I hit a problem that couldn't load data from /data/emoted.o into emote variable.

Did you meet the same problem?

**Comment by thefallentree** [comment]
You need to covert it into utf8 encoding as text file

**Comment by Yeeler** [comment]
yes, I did. all *.c *.o and config files are utf8 now.

**Comment by Yeeler** [comment]
Actually, the problem is the end of the line.
Each mapping should end with \r\n, otherwise use \r, Not \n

I was using VS Code to modify code, it will overwrite the end of the line with \n or \r\n
Notepad++ resolved my problem.
