### ISSUE TITLE
Any recommended mud client to use?

### ISSUE THREAD

**Issue by Yeeler** [fluffos/xkx100#4]
Hi @oiuv,

I am converting Fengyun 2005 mudlib into utf-8 too. Zmud 7 and Mushclient 5.6 can show utf-8 Chinese, but they not work well with inputted ones. Mudlet has better support on utf-8. It supports both input and output utf-8 Chinese. But its UI is relatively simple, comparing to zmud.

What mud client are you using?

**Comment by oiuv** [comment]
I like [tintin++](https://github.com/scandum/tintin), if you wanna use zmud，use GBK encoding output。

**Comment by Yeeler** [comment]
Thanks. I will try it out.
